ENV_OLLAMA_URL = 'OLLAMA_URL'
ENV_DIR_AI_RAG = 'DIR_RAG'

DEFAULT_OLLAMA_URL = 'http://ollama:11434'
DOMAIN_OLLAMA_RELAI = 'ollama_relai'

REDIS_SESSIONS_DB = 2

CHAT_TYPE_INTERACTIVE = 'chat'
CHAT_TYPE_KNOWLEDGE = 'knowledge_query'

MODEL_TYPE_KNOWLEDGE = 'knowledge_model_name'
